### ISSUE TITLE
Bootstrap conflict

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Casper#357] opened 2017-08-12 20:00 UTC
### Screenshot

<img width="1261" alt="screen shot 2017-08-12 at 3 55 25 pm" src="https://user-images.githubusercontent.com/6694151/29243826-b5ff8e28-7f76-11e7-8ccc-21aa0fab1a99.png">

### Steps to Reproduce
 
I tried to use Bootstrap v4.0.0-alpha.6 (https://getbootstrap.com)
is order to use the fancy button they made

The issue is that it mess with the ratio of many element in the theme.
It would be great to be able to use bootstrap4 (bootstrap.min.css & bootstrap.min.js) without any conflict or to integrate it directly in the theme.

My requirement really is to get great button to make call to action in my content.

### Technical details:

- Ghost Version: 1.5.2 (via the official Docker hub image)
- Casper version 2.0.2
- Browser version: Chrome 60.0.3112.90 (Official Build) (64-bit)
- OS Version: Mac OS X 10.11.6
- Environment production
- Node Version: v6.11.2
- Database: sqlite3
- Mail SMTP

**Comment by kevinansfield** [comment] 2017-08-14 09:02
@pascalandy I'm going to close this as it's not a bug - Casper is designed as a standalone theme, if you want to integrate it with other CSS frameworks that's your prerogative but it's not something that we're going to address in core.

**Closed by kevinansfield** 2017-08-14 09:02 UTC
