### ISSUE TITLE
Next Post Footer - Shown number of posts is wrong

### ISSUE THREAD

**Issue by styxlab** [TryGhost/Casper#684] opened 2020-02-19 19:36 UTC
### Description

The shown number of posts in the *Links to Previous/Next posts* section at the bottom of all **posts** should be increased by 1. For example, scroll down on the [Ghost Demo Page](https://demo.ghost.io/welcome/) you'll see a button saying [See all 6 posts →](https://demo.ghost.io/tag/getting-started/). When you click on the Link, 7 posts are displayed. Thus, the shown number should be 7 on the button instead of 6. The problem is present in all posts.

### Technical details

The problem arises in `post.hbs` where three related posts are fetched excluding the current one:
```
 {{#get "posts" filter="tags:{{primary_tag.slug}}+id:-{{id}}" limit="3" as |related_posts|}}
```
Within this context, `meta.pagination.total` seems to exclude the current post ending up with one less. The button links to `/tag/slug`, therefore all posts tagged with this `slug` are shown which includes the current post.

### Possible solutions

1. Add one to  `meta.pagination.total` in `post.hbs` **OR**
2. Change the `meta.pagination.total` in the upstream code (it's interesting that the total number does no depend on the `limit` of the fetched posts, so maybe this should be fixed upstream instead)

### Expectation

The shown number of posts on the button link should equal the number of posts when shown after clicking on this link.

**Comment by kevinansfield** [comment] 2020-02-19 20:32
This is a duplicate of https://github.com/TryGhost/Casper/issues/488

**Comment by styxlab** [comment] 2020-02-19 20:59
Sorry I missed that old issue — still not solved though.

**Comment by vikaspotluri123** [comment] 2020-02-20 02:34
> Why not add just +1 to the current calculation

Handlebars is a templating engine which doesn't support addition 😉

**Comment by styxlab** [comment] 2020-02-20 08:56
You could add a little math helper to handlebars for this purpose, but I agree that this issue should be solved in the core {#get} helper and not in the view.

**Comment by kevinansfield** [comment] 2020-02-20 11:20
The `meta.pagination.total` number that is returned from core is correct for what is being requested so there's nothing to fix upstream.

There are available workarounds in the theme, such as the one implemented in https://github.com/kevinansfield/Casper/commit/325b6a808542b3fdf6da21f1e9333d46723fcdec which works but was deemed to complicate Casper's code too much (Casper is designed to be a basic+accessible introduction to Ghost themes). However you are free to implement that or something similar in your own site's theme if you want.

Closing as this is a duplicate of https://github.com/TryGhost/Casper/issues/488 and is re-hashing discussions from that issue.

**Closed by kevinansfield** 2020-02-20 11:20 UTC

**Comment by styxlab** [comment] 2020-02-20 12:16
Instead of excluding the current post in the query field you should add another filter option to exclude the current post (similar to the limit option). That way the `meta.pagination.total` returned would be correct and the theme code would be untouched. Kind of sad, that these bugs don't get fixed by your team.
