### ISSUE TITLE
Navigation Menu doesn't work if theme is opened from Facebook Application

### ISSUE THREAD

**Issue by andrewmur** [TryGhost/Casper#380] opened 2017-09-04 14:19 UTC
### Screenshot

![Menu Defect screenshot_2017-09-04-17-05-10](https://user-images.githubusercontent.com/6359495/30030459-0a612248-9196-11e7-8995-869116593b18.png)

### Steps to Reproduce
 
 1. Share link to Casper Theme or Blog (which is based on Casper 2.1.0) 
 2. Try to Open it in Facebook application on Mobile

**Expected result:**
Menu should work fine in Facebook App like in browser (e.g. Chrome)
Floating Header shouldn't overlap with Facebook "Share this" plaque

**Actual result**
Navigation Menu doesn't open at all.

### Technical details

* Casper Version: 2.1.0
* Ghost Version: 1.8.0 - 1.8.1
* Browser Version: Facebook Application
* OS Version: Android Oxygen

**Comment by AileenCGN** [comment] 2017-09-19 03:36
This works fine on Facebook for iOS. Will try to find an Android device to reproduce this issue.

**Comment by AileenCGN** [comment] 2017-09-19 04:27
Alright, found an Android device (Google Pixel, running Oreo), but it works fine out of the Facebook app. See:

![casper_fb_app_oreo_closed](https://user-images.githubusercontent.com/8037602/30575725-fbbb3f6a-9d2c-11e7-9358-dc015e9b930b.png)
![casper_fb_app_oreo_open](https://user-images.githubusercontent.com/8037602/30575728-fd6a1340-9d2c-11e7-83f2-149dcee6b00f.png)

**Comment by AileenCGN** [comment] 2017-09-27 11:21
I am closing this issue, as I am not able to reproduce it and it seems more likely to be an issue with the used Facebook app in this Android version.

Please feel free to reopen it, when there are more details available on how to reproduce it / we know, where the issue is.

**Closed by AileenCGN** 2017-09-27 11:21 UTC
Labels: needs info

**Comment by andrewmur** [comment] 2017-10-05 14:33
@AileenCGN Facebook version 141.0.0.31.91
