### ISSUE TITLE
Overlay at banner covers the main content

### ISSUE THREAD

**Issue by ndaidong** [TryGhost/Casper#358] opened 2017-08-14 07:42 UTC
There is something wrong with the new banner in Casper v2.0.3. It appears an overlay that covers a part of main content. I've checked the CSS properties but didn't find out any difference in comparison with recent version.

### Screenshot

![](http://i.imgur.com/wUdELdv.png)

### Steps to Reproduce
 
 1. Update Casper to v2.0.3
 2. Restart server
 3. Go to homepage

### Technical details

* Casper Version: 2.0.3
* Ghost Version: 1.5.2
* Browser Version: Chrome 60
* OS Version: Linux Mint 18.2

**Comment by ErisDS** [comment] 2017-08-14 08:18
Closing this cos it's a duplicate of #349

**Closed by ErisDS** 2017-08-14 08:18 UTC
