### ISSUE TITLE
Editor vs Reality

### ISSUE THREAD

**Issue by doncabreraphone** [TryGhost/Casper#845] opened 2022-03-06 22:26 UTC
I’m somewhat confused here. I installed Ghost with Casper locally, and so far, I’m seeing huge differences between what the Editor shows and what I see once I preview my posts.
It’s gotten to the point where differences are so abysmal that I have to use HTML snippets to keep consistency.

The Editor looks excellent, but it differs significantly from what I end up seeing, and since Casper is the “default” theme for Ghost, I was expecting to see at least some design coherence, but so far, I’m left speechless by how inaccurate and different some of the features are.

Here’s the editor version:
![image](https://user-images.githubusercontent.com/45015326/156944720-321e8f28-527b-4e3d-afe9-d7f7b6f2afbf.png)

And here is what I get when I publish the site.

![image](https://user-images.githubusercontent.com/45015326/156944732-bdea7e81-c785-4b17-90de-6f2945c228d4.png)

What’s the point in introducing a new feature if there is no way for me to use it? It doesn’t even creates the styles once I press “Publish”.

Casper: 4.7.3
Ghost: 4.8

I’m using ghost locally.

Are those features something for paid customers only? If so, it should say so explicitly on the website.

**Comment by minimaluminium** [comment] 2022-03-08 10:40
Closing this because the issue isn't specific to the theme and was reported by @doncabreraphone in https://github.com/TryGhost/Ghost/issues/14278

**Closed by minimaluminium** 2022-03-08 10:40 UTC
