### ISSUE TITLE
Releated posts appears also if primary tag is not equal

### ISSUE THREAD

**Issue by Playrom** [TryGhost/Casper#673] opened 2019-12-31 16:11 UTC
### Screenshot

<img width="1531" alt="Screenshot 2019-12-31 at 17 04 47" src="https://user-images.githubusercontent.com/2163357/71626889-b27dfa00-2bef-11ea-981d-49c40b940d12.png">

### Steps to Reproduce
 
 1. Put all previous posts to an internal tag, all the posts must have only this tag ( ex. TAG-ONE )
 2. Create a new post that has a new different public tag, and only that tag ( ex. TAG-TWO )
 3. Those two tags are the only ones in the blog

Becouse there is no tag "in common" between the newest post and the other, the releated posts block must be empty, becouse there is no primary tag in common between this post with TAG-TWO and the others which have TAG-ONE , but one post from the others appears in the block

If i go to the other post page, in the releated block appears one post of TAG-ONE ( correctly ) and the TAG-TWO one ( wrongly )

I don't know if can be usefull, but i'm filtering out from Home Page all the posts which have TAG-ONE, using this routes.yaml, which also define an archive page with all the TAG-ONE posts

[routes.yaml.zip](https://github.com/TryGhost/Casper/files/4013047/routes.yaml.zip)

### Technical details

* Casper Version: 3.0.5
* Ghost Version: 3.2.0
* Browser Version: Chrome latest
* OS Version: Ubuntu 18.04

**Comment by gargol** [comment] 2020-03-05 03:30
Hi @Playrom! I believe what you see is not a bug but a designed behaviour of the theme. The two posts you see are **not** "related" they are [next and previous](https://github.com/TryGhost/Casper/blob/ff51925/post.hbs#L163-L171) posts

Related posts appear in a different box that looks something like this:
![Screenshot from 2020-03-05 11-28-40](https://user-images.githubusercontent.com/675397/75945202-88d59d80-5ed4-11ea-97ab-c57601e20974.png)

Closing it for now, but feel free to reopen if I misunderstood something ;)

**Closed by gargol** 2020-03-05 03:30 UTC
