### ISSUE TITLE
Feature: sub-content linking for headings

### ISSUE THREAD

**Issue by Bilge** [TryGhost/Casper#390] opened 2017-09-24 23:20 UTC
Headings have always had unique IDs, but one has to source-dive to find it, thus making sub-content linking difficult. Many sites show a paragraph marker (¶) next to headings on mouse-over, which when clicked, creates a link to that heading. The specific implementation is left to your discretion, but linking to specific parts of a document is an important feature.

**Comment by vikaspotluri123** [comment] 2017-09-25 01:06
Looks like a duplicate of #373

**Comment by kevinansfield** [comment] 2017-09-25 08:43
Closing as a duplicate of #373

**Closed by kevinansfield** 2017-09-25 08:43 UTC
