### ISSUE TITLE
[Footer] If not enough content, footer is not positioned correctly

### ISSUE THREAD

**Issue by lightningboss** [TryGhost/Casper#362] opened 2017-08-15 21:01 UTC
<img width="669" alt="screen shot 2017-08-15 at 23 00 06" src="https://user-images.githubusercontent.com/11751444/29336258-8269f212-820d-11e7-9ba6-c144b904bac3.png">
### Steps to Reproduce
 
 1. Set up new blog
 2. Remove all example posts but one
3. Go to front page

### Technical details

* Casper Version: 2.0.2
* Ghost Version: 1.5.1
* Browser Version: Chrome Version 60.0.3112.90
* OS Version: macOS 10.12.6

**Comment by vikaspotluri123** [comment] 2017-08-15 21:08
Looks like a duplicate of #354

**Comment by lightningboss** [comment] 2017-08-15 21:28
Yep, see my comment there.

**Closed** 2017-08-16 10:57 UTC
