### ISSUE TITLE
Localisation support / Multilanguage

### ISSUE THREAD

**Issue by mentat-fr** [TryGhost/Casper#671] opened 2019-12-22 18:23 UTC
Casper rock's and it would be soy great to add this localisation feature in Casper 3.0.
There is lot more English with members feature and future ...

I know there is https://github.com/juan-g/WorldCasper2 but it's not seem to follow official update.
It'll be demonstrate the localisation feature for themes too ;)
https://ghost.org/blog/theme-translations/

Thx you.

**Comment by kevinansfield** [comment] 2019-12-22 22:34
Closing as a duplicate of of https://github.com/TryGhost/Casper/pull/306#issuecomment-479492611 and https://github.com/TryGhost/Casper/issues/555

**Closed by kevinansfield** 2019-12-22 22:34 UTC
