### ISSUE TITLE
Post pages become foggy when sliding to the foot

### ISSUE THREAD

**Issue by makerdiary** [TryGhost/Casper#386] opened 2017-09-19 14:41 UTC
Hi guys,
I encountered a problem: After enabling subscribers function, the post page will become foggy when sliding to the foot.

### Screenshot
<img width="1207" alt="2017-09-19 10 32 17" src="https://user-images.githubusercontent.com/8767354/30597725-7007da74-9d8a-11e7-9489-f80befdd11ce.png">

### Steps to Reproduce
 
 1. open https://demo.ghost.io/welcome/ , and sliding to the foot.

### Technical details

* Casper Version: 2.1.2
* Ghost Version: 1.8.6
* Browser Version: Chrome
* OS Version: macOS and Win10

**Comment by kirrg001** [comment] 2017-09-19 14:45
@makerdiary 

Closing, because this looks like a duplicate of https://github.com/TryGhost/Casper/issues/340.
If this turns out to be a different issue, please reply 👍

**Closed by kirrg001** 2017-09-19 14:45 UTC
