### ISSUE TITLE
Did the dark theme disappear from v4?

### ISSUE THREAD

**Issue by Coder-Iro** [TryGhost/Casper#794] opened 2021-04-08 03:52 UTC
In v3, there was a dark theme that was automatically applied according to the system theme. But after updating to v4, I found out that the dark theme disappeared. Is the dark theme permanently gone? Or do you have any plans to make it?

**Comment by minimaluminium** [comment] 2021-04-08 04:19
Duplicate of [a discussion](https://forum.ghost.org/t/casper-dark-theme-is-gone-in-ghost-4-0/21037) on the forum.

**Closed by minimaluminium** 2021-04-08 04:19 UTC
