### ISSUE TITLE
When linking to an anchor on the page the blog title/progress bar overlaps the anchor location 

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Casper#471] opened 2018-08-14 21:21 UTC
For example, when I link to the comments section on my posts, the top of the comment box is hidden under the progress bar.

I'd prefer the scroll position to be about 40px up.

https://jessehouwing.net/vsts-relnote-ci-cd-tools-for-vsts-extensions-1-1-75/#comments

**Comment by vikaspotluri123** [comment] 2018-08-14 21:37
Hey @jessehouwing 👋 this is a duplicate of #369 and #444

**Closed** 2018-10-01 10:02 UTC
