### ISSUE TITLE
v5.1.3  Distorted feature images in grid view

### ISSUE THREAD

**Issue by boycottseattle** [TryGhost/Casper#867] opened 2022-06-02 05:11 UTC
Something changed and broke in the newest version of Casper.

**Comment by komrad** [comment] 2022-06-02 13:17
Same issue here, aspect ratio isn't square anymore

**Comment by minimaluminium** [comment] 2022-06-03 02:30
Hey everyone! Would you be able to provide some example where I can test? Site URL, screenshot and browser version would help a lot.

**Comment by jcgallaher** [comment] 2022-06-03 03:01
@minimaluminium I looked at my site and switched from the default view to grid view in the preview menu to test it. I do see a difference between the two. However I'm not sure if it is as intended or if it's the same issue they mentioned. I like the default view, but here's two screenshots from my site to show:

This is the default view:
![Screenshot_default](https://user-images.githubusercontent.com/84199958/171777787-619b0e5f-6070-407f-81cf-ba389af39710.png)

This is the grid view:
![Screenshot_grid](https://user-images.githubusercontent.com/84199958/171778117-866662ee-0ec0-4526-9e2c-962c79cd078d.png)

**Comment by boycottseattle** [comment] 2022-06-03 04:04
That is indeed how mine looks, and it’s not supposed to. Prior to this version, it showed the full featured image and scaled it appropriately, not some awful weird vertical crop.

**Comment by komrad** [comment] 2022-06-03 07:06
> Hey everyone! Would you be able to provide some example where I can test? Site URL, screenshot and browser version would help a lot.

You can see an example on https://wigglywaves.com/

**Comment by minimaluminium** [comment] 2022-06-03 09:13
Hey again! This is now fixed in [5.1.4](https://github.com/TryGhost/Casper/releases/tag/v5.1.4). Thumbnails should now be displayed fully and scaled properly without any cropping while using the List layout.

**Closed by minimaluminium** 2022-06-03 09:13 UTC

**Comment by minimaluminium** [comment] 2022-06-03 09:21
Not related to the bug mentioned in this issue, we deliberately changed the grid layout to keep the original image aspect ratio and provide more variety between the layouts. If you prefer consistent aspect ratio, you could either use the default layout or add custom CSS as code injection to force same aspect ratio.

**Comment by jcgallaher** [comment] 2022-06-03 12:14
@minimaluminium Thanks for your quick work!

**Comment by boycottseattle** [comment] 2022-06-03 12:32
Yay!!! Thank you!!!

**Comment by mbajkowski** [comment] 2022-07-05 01:50
@minimaluminium regarding your comment on the deliberate change for the grid layout in 5.0. To revert to the previous consistent aspect ratio behavior is the following sufficient in the css or is there a better way?

`.post-card-image {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 200px;
    background: var(--color-lightgrey) no-repeat 50%;
    -o-object-fit: cover;
    object-fit: cover;
}`

**Comment by minimaluminium** [comment] 2022-07-19 07:45
@mbajkowski The CSS below should be enough.

```css
.post-card-image-link:after {
    padding-bottom: 55% !important;
}

.post-card-image {
    position: absolute !important;
}
```
