### ISSUE TITLE
Post image max-width is greater than container and/or off-center

### ISSUE THREAD

**Issue by stoqe** [TryGhost/Casper#322] opened 2017-07-08 02:55 UTC
Meaning larger images display like this...
![ghost-post-full-content-img](https://user-images.githubusercontent.com/1171169/27982064-37806c62-63dc-11e7-9b3b-1dcea6223833.png)

**Comment by shadowframe** [comment] 2017-07-16 23:44
And on mobile device like the iPhone the image is to big.
As result yo can not see the edges

**Comment by AileenCGN** [comment] 2017-07-17 02:32
Hey @stoqe! Would you mind providing more information about this? When I upload a large image, it's never larger than the parent container and stays within the max-width of 1040px. It's also centered for me.

@shadowframe I can confirm this behaviour on mobile. Not sure if this is intended, cc @JohnONolan?

**Comment by AileenCGN** [comment] 2017-07-19 04:51
I am able to reproduce this, when I'm running Casper 2.0 on Ghost 0.11.11, but not on Ghost 1.0

**Comment by shadowframe** [comment] 2017-07-19 11:52
![image](https://user-images.githubusercontent.com/2557742/28365591-7ca9290e-6c89-11e7-80e3-d4d6b92c8835.png)

ghost 1.0

**Comment by JohnONolan** [comment] 2017-07-20 13:29
@stoqe Casper 2.0 is not supported on Ghost LTS. If you want to use the new design you'll need to use Ghost 1.0. Compatibility is specified in package.json

@shadowframe That is a completely different bug (please open a separate issue next time) - but it should now be fixed in master :) thanks for reporting, that was an ugly one!

**Closed by JohnONolan** 2017-07-20 13:29 UTC
Labels: bug, mobile, styles
