### ISSUE TITLE
The site design preview is now broken.

### ISSUE THREAD

**Issue by boycottseattle** [TryGhost/Casper#831] opened 2021-12-14 00:25 UTC
Using the latest version of Ghost with Casper 4.5 breaks the page preview on the design page.

**Comment by minimaluminium** [comment] 2021-12-14 04:42
Hey @boycottseattle, just checked with the latest version of Ghost and Casper, but couldn't reproduce the issue. Would you be able to send a screenshot, and see if there's any console error when on the design screen?

**Comment by boycottseattle** [comment] 2021-12-14 06:09
Screenshot? No point...it just shows blank. Nothing there. Just blank.

**Comment by minimaluminium** [comment] 2022-01-03 01:58
The issue wasn't reproducible, so I'm closing this one. If you still encounter this, make sure to reopen the issue.

**Closed by minimaluminium** 2022-01-03 01:58 UTC
