### ISSUE TITLE
Animated text is not being rendered properly on Chrome

### ISSUE THREAD

**Issue by camilodelvasto** [TryGhost/Casper#221] opened 2015-10-07 16:19 UTC
On Chrome (and possibly Safari too) the animated text and other H2/H3 elements are not being properly rendered on the default theme (Casper). We fixed this for our blog using:
html { -webkit-font-smoothing: antialiased; }
I suggest adding this line to Casper.

**Comment by JohnONolan** [comment] 2015-10-09 06:38
Hey there, not sure what you mean by animated text? Would you be able to provide a few more details to help understand what you're seeing? Preferably including screenshots/screencasts

**Comment by camilodelvasto** [comment] 2015-10-09 20:34
Just check here: http://demo.ghost.io/  - the `h2.page-description`  (a beautiful narrative...) gets bolder after the animation finishes on chrome. Screenshots:

![screenshot 2015-10-09 15 30 31 3](https://cloud.githubusercontent.com/assets/4598282/10404899/2a3ac436-6e9b-11e5-8b72-ffea7b410000.png)
![screenshot 2015-10-09 15 30 32](https://cloud.githubusercontent.com/assets/4598282/10404900/2a3b37fe-6e9b-11e5-86ee-3edf46841ac3.png)
![screenshot 2015-10-09 15 30 30](https://cloud.githubusercontent.com/assets/4598282/10404901/2a3e088a-6e9b-11e5-9ad3-ac13b99d419c.png)

This can be fixed by adding:
`html { -webkit-font-smoothing: antialiased; }` to the stylesheet.

**Comment by JohnONolan** [comment] 2015-10-13 07:40
I'm able to reproduce the issue, but I'm generally hesitant to add any style rules to the HTML selector for performance reasons, particularly with something like this when it's not already included in [Normalize](https://github.com/necolas/normalize.css/blob/master/normalize.css) - because that usually points to a larger issue.

Any thoughts @kevinansfield ?

**Comment by kevinansfield** [comment] 2015-10-13 10:12
The header is the only place where it's particularly visible so I would suggest applying the change only to that text: `div.main-header-content.inner { -webkit-font-smoothing: antialiased; }`

Applying it to `html` would mean that sub-pixel font rendering is lost everywhere which seems like a poor tradeoff even before performance implications are taken into consideration.

**Comment by margemcm** [comment] 2017-03-22 01:30
I'm curious if a fix is still wanted for this -- the text "hops" a little at the end, but doesn't seem to get bolded as it is on the demo site

**Comment by JohnONolan** [comment] 2017-06-19 12:35
This has been open for 2+ years :) closing until someone else reports or fixes

**Closed by JohnONolan** 2017-06-19 12:35 UTC
