### ISSUE TITLE
Automatic Dark Switching, or Dark Mode

### ISSUE THREAD

**Issue by kesenwang** [TryGhost/Casper#774] opened 2021-03-16 08:04 UTC
Sorry, was automatic switching between light and dark modes actually removed for the 4.0 release? I'm not even seeing any option at all to enable this, or even set a light/dark option for devices. Please say this hasn't been removed and we don't have to edit theme .css

**Comment by goranche** [comment] 2021-03-17 08:27
Not sure if this is what you mean, but there is a button at the bottom of the sidebar:

<img width="616" alt="Screen Shot 2021-03-17 at 09 26 29" src="https://user-images.githubusercontent.com/1487971/111437043-f2e96b00-8702-11eb-9877-fc2a92338502.png">

**Comment by joch** [comment] 2021-03-17 20:44
Seeing the same thing. Seems to be stuck on bright mode.

@goranche the issue is with the site itself, and not the admin site.

**Comment by liveforeverx** [comment] 2021-03-17 20:55
I found an option, how to enable it:

```
<script>document.documentElement.classList.add('dark-mode');</script>
```

In code injection, but than the links become dark on dark and not possible to see. It is possible to enable manually, but dark mode is broken.

**Comment by kesenwang** [comment] 2021-03-18 15:13
> Seeing the same thing. Seems to be stuck on bright mode.
> 
> @goranche the issue is with the site itself, and not the admin site.
> 
> Reverted back to v3 until this and #775 is fixed.

Is this issue just site-side? 

> Not sure if this is what you mean, but there is a button at the bottom of the sidebar:
> 
> <img alt="Screen Shot 2021-03-17 at 09 26 29" width="616" src="https://user-images.githubusercontent.com/1487971/111437043-f2e96b00-8702-11eb-9877-fc2a92338502.png">

Dark mode switching is working on the backend but not being pushed to front end.

**Comment by JohnONolan** [comment] 2021-03-18 15:53
We had many complaints about the auto-switching behavior on the front end so we changed it to manual. It’s now light by default, if you want dark, add this to code injection:

```
<script>document.documentElement.classList.add('dark-mode');</script>
```

if you want it to switch automatically, you can edit the theme CSS and use a media query, or use JS to detect/apply. Lots of options! Feel free to discuss/share ideas over on our developer forum forum.ghost.org - closing the issue here because it’s not a bug :)

**Closed by JohnONolan** 2021-03-18 15:53 UTC

**Comment by kesenwang** [comment] 2021-03-18 16:46
> We had many complaints about the auto-switching behavior on the front end so we changed it to manual. It’s now light by default, if you want dark, add this to code injection:
> 
> ```
> <script>document.documentElement.classList.add('dark-mode');</script>
> ```
> 
> if you want it to switch automatically, you can edit the theme CSS and use a media query, or use JS to detect/apply. Lots of options! Feel free to discuss/share ideas over on our developer forum forum.ghost.org - closing the issue here because it’s not a bug :)

 I’ll just correct that response for a moment here. There’s a difference between automated switching between light and dark depending on device specifications/locale or whatever functions you guys grab device side I’m assuming light/dark on iPhones.

Why the inclusion of being able to switch light/dark on the admin panel? This doesn’t replicate front-end?

**Comment by JohnONolan** [comment] 2021-03-18 17:15
I don't know what you think you're correcting - the light/dark mode of the admin panel has nothing to do with the front end.

If you need help understanding how to use the product, feel free to use our forum.
