### ISSUE TITLE
gulp default command seems to hang

### ISSUE THREAD

**Issue by jwir3** [TryGhost/Casper#423] opened 2018-01-17 17:08 UTC
### Screenshot

<img width="396" alt="screen shot 2018-01-17 at 11 05 55 am" src="https://user-images.githubusercontent.com/997106/35056079-7581f2f6-fb76-11e7-8d79-77c737ef1c86.png">

### Steps to Reproduce
 
 1. Clone this repository.
 2. Navigate to directory, run `npm install`.
 3. Run `gulp`.

It doesn't seem as though the `default` task (or the `build` task, if I run that independently) finishes. Or, rather, the task finishes, but gulp never returns to the command line for me.

### Technical details

* Casper Version: 2.1.8 (`master`)
* OS Version: macOS Sierra 10.12.6
* Node Version: 8.9.3
* Npm Version: 5.6.0

**Comment by acburdine** [comment] 2018-01-17 17:11
@jwir3 the default gulp command is intended to watch for changes in the source CSS file and then rebuild (as indicated by the "starting watch" task).

Closing as this is intentional behavior and not a bug.

**Closed by acburdine** 2018-01-17 17:11 UTC

**Comment by acburdine** [comment] 2018-01-17 17:12
Looking at it again - the reason `gulp build` hangs is because of #420.
