### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by chenxsan** [TryGhost/Casper#154] opened 2015-01-03 12:07 UTC
When view http://demo.ghost.io/ with firefox console opened, I got some error messages:

![ghost](https://cloud.githubusercontent.com/assets/1091472/5602377/f7cad060-9383-11e4-9d03-291c89c6754e.jpg)

> downloadable font: OS/2: bad linegap: -32 (font-family: "casper-icons" style:normal weight:normal stretch:normal src index:1)
source: http://demo.ghost.io/assets/fonts/casper-icons.woff screen.css
> downloadable font: OS/2: bad weight: 250 (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2)
source: https://fonts.gstatic.com/s/merriweather/v8/ZvcMqxEwPfh2qDWBPxn6nmFp2sMiApZm5Dx7NpSTOZk.woff

What's the problem? Any suggest?

**Comment by JohnONolan** [comment] 2015-01-03 12:49
Hi there - I'm not able to reproduce this I'm afraid! Could you have a read of our contributing guidelines and follow the bug report template, with a particular emphasis on technical details? https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs

**Comment by chenxsan** [comment] 2015-01-03 13:11
Hi there, some technical details here:

+ OS - openSUSE 13.2 32 bits.
+ Browser - Firefox 34.0.5, with a lots of addons

I also tried Firefox 36.0a2 with all addons disabled, same errors in the console.

No errors in Chrome(Version 40.0.2214.45 beta) console.

**Comment by JohnONolan** [comment] 2015-01-03 14:22
Sounds like it's something to do with your OS/Browser - this isn't something we've seen before. If you find a solution, feel free to PR!

**Comment by crepererum** [comment] 2015-01-14 10:58
I can reproduce this. You have to enable CSS warning/errors to see this. It seems that these errors are mostly because of
 - outdated prefixes (e.g. `white-space: -moz-pre-wrap` which [isn't required as of Firefox 3.0](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space))
 - compatibility reasons (e.g. `background: -webkit-gradient`)
 - unsupported features, at least without prefix (e.g. `word-break: break-word;`)

But there is also 1 real error:
`.clearfix { *zoom: 1; }` at `screen.css:443` should not have this `*`, right?

**Comment by JohnONolan** [comment] 2015-01-15 02:23
Wow nice find - happy to merge if you want to pr fixes for those

**Comment by crepererum** [comment] 2015-01-15 12:47
I'll prepare one :)

**Comment by JohnONolan** [comment] 2015-02-17 14:09
Fixed in #159

**Closed by JohnONolan** 2015-02-17 14:09 UTC
