### ISSUE TITLE
Blurred Page because of Subscription Overlay

### ISSUE THREAD

**Issue by pankajpatel** [TryGhost/Casper#397] opened 2017-10-03 06:53 UTC
The blog page gets blurred. It is happening because of the `last two lines` in following code:

```
.subscribe-overlay {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 9000;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-pack: center;
    justify-content: center;
    -ms-flex-align: center;
    align-items: center;
    background: rgba(0,25,40,.97);
    opacity: 0;
    transition: opacity .2s ease-in;
    pointer-events: none;
    -webkit-backdrop-filter: blur(3px);
    backdrop-filter: blur(3px);
}
```

### Screenshot

![time2hack com-](https://user-images.githubusercontent.com/251937/31099493-77734a14-a7c6-11e7-8346-bbcb87e89a89.png)

### Steps to Reproduce
 
1. Open http://time2hack.com on Chrome
2. Sometime whole page is blurred
3. Sometime blur appears when you scroll to the bottom of page

### Technical details

* Casper Version: 2.1.2
* Ghost Version: 1.9
* Browser Version: Chrome v60.0.3112.113
* OS Version: macOS Siera 10.12.6 (16G29)

**Comment by AileenCGN** [comment] 2017-10-03 07:05
Hey @pankajpatel 👋 

Closing, because this looks like a duplicate of #340.
If this turns out to be a different issue, please reply 👍

**Closed by AileenCGN** 2017-10-03 07:05 UTC

**Comment by pankajpatel** [comment] 2017-10-03 10:26
Yes it is same! Thanks for quick response!

Though it is Chrome's bug. updating it seems to have fixed it.
