### ISSUE TITLE
Fitvids makes Youtube embeds disappear in Firefox

### ISSUE THREAD

**Issue by bjj** [TryGhost/Casper#330] opened 2017-07-24 04:59 UTC
Just installed ghost 1.0.0-rc.1 on Ubuntu to experiment.  Embedding a standard Youtube video causes the video to appear briefly and then disappear when fitvids wraps it.  The video works as expected (with static size) if class="fitvidsignore"

When I happened to put a different embed ahead of it (from google docs) it did show up, but very tiny.

**Comment by AileenCGN** [comment] 2017-07-24 05:52
Hey @bjj! I'm not able to reproduce this on Ubuntu with Ghost 1.0. Could you please provide a bit more information? Maybe some logs so I'm able to reproduce this issue?

**Comment by bjj** [comment] 2017-07-24 05:59
This is the markdown for the post:

    This is my *markdown* of a _story_ which is about `code`.

    <iframe width="560" height="315" src="https://www.youtube.com/embed/2l66yRlW52Y?rel=0" frameborder="0" allowfullscreen></iframe>

Adding `class="fitvidsignore"` to that will fix it.

Can you be more specific about what logs would help you reproduce this?  There is no console output (script errors, etc).  I'm serving it from ngnix.

**Comment by AileenCGN** [comment] 2017-07-24 06:14
Yes, this is a Firefox issue! I was able to reproduce it. For me it works fine in Safari and Chrome (both on macOS), but Firefox doesn't render it.

**Comment by JohnONolan** [comment] 2017-07-31 15:39
Yeah this one was not fun at all - all down to a really horrific bug in Firefox. Committed a workaround so it should work now

**Closed** 2017-07-31 15:38 UTC
Labels: bug
