### ISSUE TITLE
Mobile Phones:  Navigation Items are Cut Off

### ISSUE THREAD

**Issue by zeitrechnen** [TryGhost/Casper#399] opened 2017-10-03 09:29 UTC
In the current realease of Casper (http://demo.ghost.io/) the navigation items are cut off.

- Occurs on single post entry pages (example: http://demo.ghost.io/welcome/)
- mobile phones with small screens (example iPhone 5 SE)
- burger menu for mobile break point would be nice

![inkedimage-1_li](https://user-images.githubusercontent.com/1907339/31118141-ae218c86-a82c-11e7-9b9f-03a207ca9f2d.jpg)

### Technical details

* Casper Version: 2.1.2
* Ghost Version: current version of Ghost(Pro)
* Browser Version: 11.0
* OS Version: iOS 11.0

**Comment by AileenCGN** [comment] 2017-10-03 09:37
Hey @zeitrechnen 👋 

I'm closing this as it's a duplicate of #344
tl;dr: the theme nav is scrollable

**Closed by AileenCGN** 2017-10-03 09:37 UTC
