### ISSUE TITLE
Why is the layout on Safari different from the official blog?

### ISSUE THREAD

**Issue by YOnoda** [TryGhost/Casper#401] opened 2017-10-10 20:30 UTC
I just installed a new Ghost and tried setting either Casper or Blog theme, but it seems that the layout is different from the official Ghost blog. My website, which I just installed and didn't add anything, looks having too big components and only shows one post per row (I didn't zoom in). This seems to happen only on Safari (macOS 13.0 and Safari 11.0). 

Here is what is shown on my blog:

<img width="640" alt="2017-10-10 17 52 27" src="https://user-images.githubusercontent.com/4002991/31408271-7d3b8f74-adf7-11e7-9740-93386909c124.png">

And here is what is shown on the official Ghost blog:

<img width="640" alt="2017-10-10 17 41 27" src="https://user-images.githubusercontent.com/4002991/31408292-8e135b7e-adf7-11e7-80ca-8a752e4e2d41.png">

Why does this happen only on Safari?

**Comment by kevinansfield** [comment] 2017-10-11 11:42
@YOnoda I'm not able to reproduce this with Safari 11 on macOS 13.

It looks as though in your first screenshot the mobile size styles are being picked up, I would suggest clearing your cache, disabling extensions in Safari and testing again. If you need more help please head over to our [Slack channel](https://slack.ghost.org).

I'm going to close this issue as it appears that it's something specific to your setup, if there is a verifiable reproduction case that points to it being a bug in Casper we can re-open.

**Closed by kevinansfield** 2017-10-11 11:42 UTC
