### ISSUE TITLE
pre 、code  css problem   white-space

### ISSUE THREAD

**Issue by yanka1** [TryGhost/Casper#450] opened 2018-04-13 08:46 UTC
Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![image](https://user-images.githubusercontent.com/18481910/38725166-097210e4-3f39-11e8-90d1-b08d5b97f2d5.png)
![]()
![image](https://user-images.githubusercontent.com/18481910/38725175-11b92418-3f39-11e8-8f1e-a528808ab740.png)
![image](https://user-images.githubusercontent.com/18481910/38725185-1a82bef6-3f39-11e8-9e35-c02a4027a97c.png)

### Steps to Reproduce
 
 1. This is the first step
The user interface of  tag eg. pre 、code，didn`t work well . 
 2. This may be the post content used to cause an issue...
white-space : pre-wrap  looks better
### Technical details

* Casper Version: 1.2.2
* Ghost Version: latest
* Browser Version: chrome safari
* OS Version: mac android  ios

**Comment by AileenCGN** [comment] 2018-04-16 03:35
Hey @yanka1 

I am not able if I understand what the issue is that you're reporting. The CSS you're referring to in your screenshot is the user agent style sheet. Just from the screenshots above and without further description, I don't really know what this

> The user interface of tag eg. pre 、code，didn`t work well .

exactly means. Maybe it's just a language issue. Would you mind swinging over to our [Ghost forum](https://forum.ghost.org) so we can look into this together?

I will close this issue for now, as I don't think it is one, but we can always reopen it.

**Closed by AileenCGN** 2018-04-16 03:35 UTC
