### ISSUE TITLE
Background of table is missing (header and content)

### ISSUE THREAD

**Issue by y1zhou** [TryGhost/Casper#549] opened 2019-03-12 14:51 UTC
### Screenshot
![Snipaste_2019-03-12_10-47-37](https://user-images.githubusercontent.com/17245097/54209519-4beaec80-44b4-11e9-8c93-7286a8c52a2f.png)

### Steps to Reproduce
 
 1. Updated to Casper v-2.9.4
 2. Open a post with markdown tables in it
 3. The background of the table is missing
 4. Tried it on an Android phone and it was normal

### Technical details

* Casper Version: 2.9.4
* Ghost Version: 2.17.0
* Browser Version: Google Chrome 72.0.3626.121
* OS Version: Windows 10 17763.316

**Comment by kevinansfield** [comment] 2019-03-12 18:12
Thanks for the report @y1zhou 👍 Closing as a duplicate of https://github.com/TryGhost/Casper/issues/548

**Closed by kevinansfield** 2019-03-12 18:12 UTC
